### ISSUE TITLE
Should we deprecate this repository ?

### ISSUE THREAD

**Issue by floross** [floross/docker-readthedocs#17]
Hi,

Since I got no time to maintain this repository and since `readthedocs` have an official docker image, should I deprecate this repository ?

I could imagine to let enter more active maintainer too, I am open to the discussion.

Any thoughts @Jmennius ?

**Comment by Jmennius** [comment]
Hi @floross,

Images available at [docker hub](https://hub.docker.com/r/readthedocs/build/) are actually images inside which actual user documentation is built, you can't run readthedocs backend with them. So the repository is still relevant I think.

Personally, I still plan to use it (didn't have a chance to really use it yet :( !) - we have some amount of compatible documentation.. Really hope we'll do it this year.

So if it doesn't bother you too much - keep it, if it does - we can move it or else.

Thanks!
