### ISSUE TITLE
Elastic Search support

### ISSUE THREAD

**Issue by scottnasello** [floross/docker-readthedocs#3]
Hello, has anyone successfully gotten the elastic search container to work for global search on a hosted instance?  I was able to get ES working but I think there is an error in the python calls to ES.

**Comment by Jmennius** [comment]
What you need is `elasticsearch:1.7-alpine` image with ICU plugin installed `/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.7.0`.
Then you should provision and reindex, see [recently contributed doc](https://github.com/Jmennius/readthedocs.org/blob/master/docs/custom_installs/elasticsearch.rst#index-the-data-available-at-rtd-database).
Not absolutely sure that's the case with current master in this repository - you may also need to install `elasticsearch==1.7.0` with pip.

P.S. Hopefully, I will open a pull with up-to-date RTD, search working, etc in coming weeks. It has been working on my desk for quite some time..

**Comment by Jmennius** [comment]
@scottnasello, ES should be working out-of-box with current master (see #4).
Please comment if you experience any issues.
Good luck!

**Comment by scottnasello** [comment]
Here's some screen shots of my new docker build with **ES GLOBAL SEARCH**.  So awesome!

1. The failing build below doesn't have a docs folder

<img width="418" alt="rtd-docker1" src="https://user-images.githubusercontent.com/8529173/44665160-1b38df00-a9ca-11e8-9d85-f100f10d06db.png">

2. The search hits are itemized by project

<img width="549" alt="rtd-docker2" src="https://user-images.githubusercontent.com/8529173/44665165-20962980-a9ca-11e8-9852-5b0a58a009a4.png">

3. RTD provides context highlighting after clicking on a hit from the Elastic Search Results

<img width="637" alt="rtd-docker3" src="https://user-images.githubusercontent.com/8529173/44665173-2429b080-a9ca-11e8-8b69-90636b5d23db.png">
