### ISSUE TITLE
Django login not working

### ISSUE THREAD

**Issue by achim-k** [floross/docker-readthedocs#6]
When running the following command, the readthedocs instance is successfully launched. However, when accessing the web interface (http://localhost/admin) and logging in (admin/admin), nothing happens. The forwarding to the next page is not working or Django thinks that I'm still not authorized. Any ideas what could be the issue here?

```
docker run -e RTD_PRODUCTION_DOMAIN=docs.example.com -e RTD_USE_SUBDOMAIN=false \
           -e RTD_ALLOW_PRIVATE_REPOS=true -p 80:80 readthedocs
```

<details>
<summary>Docker log</summary>
<pre>
$ docker run -e RTD_PRODUCTION_DOMAIN=docs.example.com -e RTD_USE_SUBDOMAIN=false -e RTD_ALLOW_PRIVATE_REPOS=true -p 80:80 readthedocs
2018-08-31 20:04:16,062 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2018-08-31 20:04:16,069 INFO RPC interface 'supervisor' initialized
2018-08-31 20:04:16,070 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-08-31 20:04:16,070 INFO supervisord started with pid 1
2018-08-31 20:04:17,073 INFO spawned: 'nginx' with pid 9
2018-08-31 20:04:17,076 INFO spawned: 'readthedocs-bootstrap' with pid 10
Migrating (provisioning) the database...
root:123[11]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[11]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Operations to perform:
  Apply all migrations: core, account, builds, gold, sessions, admin, guardian, tastypie, integrations, auth, sites, contenttypes, redirects, taggit, oauth, socialaccount, projects, messages_extends
Running migrations:
  Rendering model states...2018-08-31 20:04:18,852 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-08-31 20:04:18,852 INFO success: readthedocs-bootstrap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying taggit.0001_initial... OK
  Applying projects.0001_initial... OK
  Applying builds.0001_initial... OK
  Applying builds.0002_build_command_initial... OK
  Applying builds.0003_add-cold-storage... OK
  Applying builds.0004_add-apiversion-proxy-model... OK
  Applying core.0001_initial... OK
  Applying core.0002_make_userprofile_user_a_onetoonefield... OK
  Applying core.0003_add_banned_status... OK
  Applying core.0004_ad-opt-out... OK
  Applying gold.0001_initial... OK
  Applying guardian.0001_initial... OK
  Applying integrations.0001_add_http_exchange... OK
  Applying integrations.0002_add-webhook... OK
  Applying messages_extends.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying socialaccount.0001_initial... OK
  Applying socialaccount.0002_token_max_lengths... OK
  Applying oauth.0001_initial... OK
  Applying oauth.0002_combine_services... OK
  Applying oauth.0003_move_github... OK
  Applying oauth.0004_drop_github_and_bitbucket_models... OK
  Applying oauth.0005_add_account_relation... OK
  Applying oauth.0006_move_oauth_source... OK
  Applying oauth.0007_org_slug_nonunique... OK
  Applying oauth.0008_add-project-relation... OK
  Applying projects.0002_add_importedfile_model... OK
  Applying projects.0003_project_cdn_enabled... OK
  Applying projects.0004_add_project_container_image... OK
  Applying projects.0005_sync_project_model... OK
  Applying projects.0006_add_domain_models... OK
  Applying projects.0007_migrate_canonical_data... OK
  Applying projects.0008_add_subproject_alias_prefix... OK
  Applying projects.0009_add_domain_field... OK
  Applying projects.0010_migrate_domain_data... OK
  Applying projects.0011_delete-url... OK
  Applying projects.0012_proper-name-for-install-project... OK
  Applying projects.0013_add-container-limits... OK
  Applying projects.0014_add-state-tracking... OK
  Applying projects.0015_add_project_allow_promos... OK
  Applying projects.0016_build-queue-name... OK
  Applying projects.0017_add_domain_https... OK
  Applying projects.0018_fix-translation-model... OK
  Applying projects.0019_add-features... OK
  Applying projects.0020_add-api-project-proxy... OK
  Applying projects.0021_add-webhook-deprecation-feature... OK
  Applying projects.0022_add-alias-slug... OK
  Applying projects.0023_migrate-alias-slug... OK
  Applying projects.0024_add-show-version-warning... OK
  Applying projects.0025_show-version-warning-existing-projects... OK
  Applying redirects.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying socialaccount.0003_extra_data_default_dict... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying tastypie.0001_initial... OK
Building RTD's locale files...
root:123[66]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[66]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
processing locale es
processing locale ar
processing locale nb
processing locale it
processing locale uk
processing locale vi_VN
processing locale ru
processing locale fr
processing locale eu
processing locale sk
processing locale gl
processing locale zh_CN
processing locale pt_BR
processing locale ca
processing locale pl
processing locale zh_TW
processing locale en
processing locale de
processing locale ja
root:123[304]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[304]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
processing file django.po in /app/readthedocs/locale/ru/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/fr/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/en/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/pt_BR/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/zh_CN/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/nb/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/zh_TW/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/it/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/vi_VN/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/sk/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/de/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/ar/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/es/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/uk/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/eu/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/ca/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/gl/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/ja/LC_MESSAGES
processing file django.po in /app/readthedocs/locale/pl/LC_MESSAGES
Generating static assets...
root:123[329]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[329]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Copying '/app/readthedocs/static/vendor/jquery-standalone.js'
Copying '/app/readthedocs/static/vendor/jquery-ui-standalone.js'
Copying '/app/readthedocs/static/vendor/underscore.js'
Copying '/app/readthedocs/static/vendor/knockout.js'
Copying '/app/readthedocs/static/vendor/jquery-migrate-standalone.js'
Copying '/app/readthedocs/static/vendor/jquery.js'
Copying '/app/readthedocs/static/vendor/jquery-ui.js'
Copying '/app/readthedocs/static/vendor/jquery-migrate.js'
Copying '/app/readthedocs/static/vendor/underscore-standalone.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/venv/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/venv/local/lib/python2.7/site-packages/guardian/static/guardian/img/icon-yes.svg'
Copying '/venv/local/lib/python2.7/site-packages/guardian/static/guardian/img/icon-no.svg'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff2'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.ttf'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.svg'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.svg'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.eot'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.ttf'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.eot'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.woff'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/js/jquery.json-view.min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/js/highlight.pack.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/js/jquery-1.10.2.min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/js/api.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/js/bootstrap.min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/img/grid.png'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/img/favicon.ico'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/highlight.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/bootstrap-theme.min.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/font-awesome-4.0.3.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/jquery.json-view.min.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/base.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/docs/css/bootstrap.min.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff2'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.ttf'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.svg'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.eot'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/coreapi-0.1.0.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/prettify-min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/default.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/ajax-form.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/csrf.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/jquery-1.12.4.min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/bootstrap.min.js'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/grid.png'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/default.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/prettify.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap.min.css'
Copying '/venv/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap-tweaks.css'
Copying '/venv/local/lib/python2.7/site-packages/django_extensions/static/django_extensions/js/jquery.bgiframe.js'
Copying '/venv/local/lib/python2.7/site-packages/django_extensions/static/django_extensions/js/jquery.autocomplete.js'
Copying '/venv/local/lib/python2.7/site-packages/django_extensions/static/django_extensions/js/jquery.ajaxQueue.js'
Copying '/venv/local/lib/python2.7/site-packages/django_extensions/static/django_extensions/img/indicator.gif'
Copying '/venv/local/lib/python2.7/site-packages/django_extensions/static/django_extensions/css/jquery.autocomplete.css'
Copying '/venv/local/lib/python2.7/site-packages/messages_extends/static/close-alerts.js'
Copying '/app/readthedocs/projects/static/projects/js/tools.js'
Copying '/app/readthedocs/projects/static/projects/js/import.js'
Copying '/app/readthedocs/projects/static/projects/badges/passing-plastic.svg'
Copying '/app/readthedocs/projects/static/projects/badges/passing-flat-square.svg'
Copying '/app/readthedocs/projects/static/projects/badges/failing-plastic.svg'
Copying '/app/readthedocs/projects/static/projects/badges/failing-flat-square.svg'
Copying '/app/readthedocs/projects/static/projects/badges/unknown-for-the-badge.svg'
Copying '/app/readthedocs/projects/static/projects/badges/passing-for-the-badge.svg'
Copying '/app/readthedocs/projects/static/projects/badges/failing-for-the-badge.svg'
Copying '/app/readthedocs/projects/static/projects/badges/failing-social.svg'
Copying '/app/readthedocs/projects/static/projects/badges/passing-flat.svg'
Copying '/app/readthedocs/projects/static/projects/badges/unknown-plastic.svg'
Copying '/app/readthedocs/projects/static/projects/badges/passing-social.svg'
Copying '/app/readthedocs/projects/static/projects/badges/failing-flat.svg'
Copying '/app/readthedocs/projects/static/projects/badges/unknown-flat.svg'
Copying '/app/readthedocs/projects/static/projects/badges/unknown-social.svg'
Copying '/app/readthedocs/projects/static/projects/badges/unknown-flat-square.svg'
Copying '/app/readthedocs/projects/static/projects/css/import.css'
Copying '/app/readthedocs/projects/static/projects/css/admin.css'
Copying '/app/readthedocs/builds/static/builds/js/detail.js'
Copying '/app/readthedocs/builds/static/builds/css/detail.css'
Copying '/app/readthedocs/core/static/core/js/readthedocs-doc-embed.js'
Copying '/app/readthedocs/core/static/core/js/site.js'
Copying '/app/readthedocs/core/static/core/js/autocomplete.js'
Copying '/app/readthedocs/core/static/core/font/RobotoSlab-Bold.ttf'
Copying '/app/readthedocs/core/static/core/font/Inconsolata-Regular.ttf'
Copying '/app/readthedocs/core/static/core/font/FontAwesome.otf'
Copying '/app/readthedocs/core/static/core/font/Inconsolata-Bold.ttf'
Copying '/app/readthedocs/core/static/core/font/Lato-Regular.ttf'
Copying '/app/readthedocs/core/static/core/font/fontawesome-webfont.svg'
Copying '/app/readthedocs/core/static/core/font/fontawesome-webfont.ttf'
Copying '/app/readthedocs/core/static/core/font/Lato-Italic.ttf'
Copying '/app/readthedocs/core/static/core/font/RobotoSlab-Regular.ttf'
Copying '/app/readthedocs/core/static/core/font/fontawesome-webfont.eot'
Copying '/app/readthedocs/core/static/core/font/fontawesome-webfont.woff2'
Copying '/app/readthedocs/core/static/core/font/Lato-Bold.ttf'
Copying '/app/readthedocs/core/static/core/font/fontawesome-webfont.woff'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Bold.eot'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Italic.woff2'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Italic.woff'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Italic.eot'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Bold.woff2'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Regular.ttf'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Italic.ttf'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Bold.ttf'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Regular.woff2'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Bold.woff'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Regular.eot'
Copying '/app/readthedocs/core/static/core/font/lato/Lato-Regular.woff'
Copying '/app/readthedocs/core/static/core/img/loader.gif'
Copying '/app/readthedocs/core/static/core/css/theme.css'
Copying '/app/readthedocs/core/static/core/css/badge_only.css'
Copying '/app/readthedocs/gold/static/gold/payment.js'
Copying '/app/readthedocs/gold/static/gold/js/gold.js'
Copying '/app/readthedocs/payments/static/payments/css/form.css'

170 static files copied to '/app/media/static'.
Creating users...
root:123[335]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[335]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

... ... ... ... ... ... ... ... ... <User: admin>
Created admin superuser
... ... ... ... ... ... ... ... ... ... ... ... ... ... ... Created slumber user
Starting RTD backend...
2018-08-31 20:04:54,205 INFO spawned: 'readthedocs' with pid 343
root:123[343]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[343]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
root:123[349]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root:123[349]: INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2018-08-31 20:05:00,171 INFO success: readthedocs entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
readthedocs: started
2018-08-31 20:05:00,189 INFO exited: readthedocs-bootstrap (exit status 0; expected)
[31/Aug/2018 15:05:13] "GET /admin/login/?next=/admin/ HTTP/1.0" 200 1681
[31/Aug/2018 15:05:15] "POST /admin/login/?next=/admin/ HTTP/1.0" 302 0
[31/Aug/2018 15:05:15] "GET /admin/ HTTP/1.0" 302 0
[31/Aug/2018 15:05:15] "GET /admin/login/?next=/admin/ HTTP/1.0" 200 1681
</pre>
</details>

**Comment by achim-k** [comment]
Commenting the following line makes the login work for me:
https://github.com/floross/docker-readthedocs/blob/df6837fb902ca8871582a03256804367813c5a51/readthedocs/app/readthedocs/settings/container.py#L32

**Comment by achim-k** [comment]
Was because `RTD_PRODUCTION_DOMAIN` was not correctly set :man_facepalming: 
Sorry for the noise

**Comment by Jmennius** [comment]
@achim-k I'm glad you got it working!
Probably was related to `SESSION_COOKIE_DOMAIN` (its value is derived from `PRODUCTION_DOMAIN`)

**Comment by maheshpardeshi** [comment]
Thanks, bro you save my one more day.
